GET http://localhost:5126/games

###
GET http://localhost:5126/games/genres

###
GET http://localhost:5126/games/2

### CREATE GAME DATA
POST http://localhost:5126/games
Content-Type: application/json

{
  "Name": "Mortal kombat 11",
  "GenreId": 1,
  "Price": 50.00,
  "ReleaseDate": "2020-07-21"
}

###
PUT http://localhost:5126/games/2
Content-Type: application/json

 {
    "Name": "The Legend of Zelda: Breath of the Wild",
    "GenreId": 2,
    "Price": 0.99,
    "ReleaseDate": "2017-12-03"
  }

###
DELETE http://localhost:5126/games/3